development:
  host: omicron.local
  admin_mail: editor@musiquemaze.com
  default_mail: editor@musiquemaze.com
  cloudfiles_api: 015a9bb650be07f24472b86655cd2f78
  cloudfiles_user: eddieyan
  facebook_app_id: '446164918758779'
  facebook_app_secret: 'e5cdd0130d1f6fccbbcfbbc7e916d49a'
  facebook_scope: 'publish_stream, email'
  facebook_page_id: '431086373610100'
  facebook_page_url: https://www.facebook.com/pages/MusiqueMaze-LLC/431086373610100
  
test:
  host: omicron.local
  admin_mail: editor@musiquemaze.com
  default_mail: editor@musiquemaze.com
  fan_page: https://www.facebook.com/pages/MusiqueMaze-LLC/431086373610100

production:
  host: musiquemaze.com
  admin_mail: editor@musiquemaze.com
  default_mail: editor@musiquemaze.com
  cloudfiles_api: 015a9bb650be07f24472b86655cd2f78
  cloudfiles_user: eddieyan
  facebook_app_id: '446164918758779'
  facebook_app_secret: 'e5cdd0130d1f6fccbbcfbbc7e916d49a'
  facebook_scope: 'publish_stream, email'
  facebook_page_id: '431086373610100'
  facebook_page_url: https://www.facebook.com/pages/MusiqueMaze-LLC/431086373610100
