development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: musiquemaze_development
  pool: 5
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: musiquemaze_test
  pool: 5
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: musiquemaze_production
  pool: 5
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
